# Generated by Django 3.1.7 on 2021-03-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=244)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('expiracao', models.DateField()),
            ],
        ),
    ]
